version: '3.1'

services:
  control.frontend:
     image: control.frontend:TAG
     ports:
      - 7002:80
      - 7003:443
     networks:
      micros:
        ipv4_address: 172.23.0.30
     environment:
      - KEY=value

networks:
  micros:
    name: micros
    external: true
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/24
